# training params
batch_size: 30
batches_per_update: 100
entropy_coef: 0.1
lambda_: 0.95
gamma: 0.99
clip: 0.2
actor_lr: 0.0002
critic_lr: 0.0001
n_iter: 10000
min_episodes_per_update: 4
min_transitions_per_update: 2000
device: cuda

# env_params
width: 20
height: 20
max_rooms: 3
min_room_xy: 5
max_room_xy: 12
max_steps: 2000
vision_radius: 5
observation_size: 11
action_dim: 3
out_dim_critic: 1
reward: custom

# model params
conv_filters: [
  [16, (3, 3), 2], 
  [32, (3, 3), 2], 
  [32, (3, 3), 1]]
lin_layers: [32]

# other params
ckpt_dir: './checkpoints'
save_freq: 50
eval_freq: 10